title: Approches de la complétion des Headers MEI par les GT1 & GT2 du Consortium-HN Musica2
description: Guideline MEI proposé par Musica2
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

markdown: kramdown

kramdown:
  input: GFM
